### ISSUE TITLE
PK - Private key passsword can't be empty

### ISSUE THREAD

**Issue by Msegun** [arrowhead-f/ArrowheadESP#4]
Hello

We're currently writing a client for ESP32. But we encountered a problem.
We did generate certificates through openssl but when we try to create connection to AHF we're receicing error 
"[start_ssl_client():191]: (-15360) PK - Private key password can't be empty"
Do you have any idea what could've gone wrong?

**Comment by tsvetlin** [comment]
Care to explain?

**Comment by Msegun** [comment]
Sorry i clicked "Enter" too fast : P

**Comment by Msegun** [comment]
Ah and we're using WiFiClientSecure object instance for connection. I know it's not much information to go on but probably someone encountered a similar problem before.

**Comment by tsvetlin** [comment]
This library does not work on ESP32 in my experience. BearSSL is not implemented for ESP32 :(
