### ISSUE TITLE
error: 'class BearSSL::WiFiClientSecure' has no member named xxx

### ISSUE THREAD

**Issue by SebCanet** [arrowhead-f/ArrowheadESP#6]
Hi,
I tried to compile (on Arduino IDE 1.8.15 & 2.0) your example to a generic esp8266 module, but I have 3 errors:

```
b:\Projets\arduino-ide_2.0.0-beta.7_Windows_64bit\portable\libraries\ArrowheadESP\src\ArrowheadESP.cpp:85:61: error: 'class BearSSL::WiFiClientSecure' has no member named 'loadCACert'
   85 |         if (getArrowheadHTTPSClient().getWiFiClientSecure().loadCACert(getArrowheadESPFS().getCA())) {
      |                                                             ^~~~~~~~~~
b:\Projets\arduino-ide_2.0.0-beta.7_Windows_64bit\portable\libraries\ArrowheadESP\src\ArrowheadESP.cpp:93:61: error: 'class BearSSL::WiFiClientSecure' has no member named 'loadCertificate'
   93 |         if (getArrowheadHTTPSClient().getWiFiClientSecure().loadCertificate(getArrowheadESPFS().getCl())) {
      |                                                             ^~~~~~~~~~~~~~~
b:\Projets\arduino-ide_2.0.0-beta.7_Windows_64bit\portable\libraries\ArrowheadESP\src\ArrowheadESP.cpp:101:61: error: 'class BearSSL::WiFiClientSecure' has no member named 'loadPrivateKey'
  101 |         if (getArrowheadHTTPSClient().getWiFiClientSecure().loadPrivateKey(getArrowheadESPFS().getPK())) {
      |                                                             ^~~~~~~~~~~~~~
```

It seems your library lacks some information in constructor class.
Thanks to fix it.

**Comment by tsvetlin** [comment]
Hello!

This error is familiar when the board is set to ESP32, because the BearSSL library does not contain these functions.
Please make sure you are setting the board to ESP8266

#3

**Comment by SebCanet** [comment]
Thanks for answering so fast, and yes it's set to ESP8266 generic module, I have just uploaded a DHT11 test code on my microcntroller. So wihtout changing settings in IDE I have this issue.
Even with an empty program with just definition "#include <ArrowheadESP.h>" there's the same error.
Even with "Adafruit Feather Huzzah ESP8266", or "Generic ESP8266 Module", or "Sparkfun ESP8266 Thing"

**Comment by tsvetlin** [comment]
I'll try to upload the code on my machine to an esp8266 and replicate the issue.

**Comment by tsvetlin** [comment]
I managed to upload the code and make it work, without any issues.
What I did: I installed the libraries in the readme. Then I installed SPIFFS (https://randomnerdtutorials.com/install-esp8266-filesystem-uploader-arduino-ide/) 
I installed the library (downloaded the zip then (Sketch -> Include Library -> Add zip library.

I opened the Basic example and modified the json files in the data folder, uploaded them with SPIFFS. Then I uploaded the code.

Maybe I should make a video guide for the library.

**Comment by SebCanet** [comment]
Hi,
many thanks for testing, in fact the pb is due to compiling in Arduino IDE. In the README of this repo you should explain that we HAVE to use SPIFF method to upload file on ESP8266.

**Comment by tsvetlin** [comment]
Note: these three functions were removed from the ESP board library 3.0.0, make sure to use an older version, until this library is not updated.

<img width="912" alt="Screenshot 2021-06-22 at 14 01 19" src="https://user-images.githubusercontent.com/15650896/122921118-6afaa900-d362-11eb-8abb-8a0b9bdbf22c.png">

**Comment by SebCanet** [comment]
Hi,
I've just tested and you're right ! For compilation the v2.7.4 works, and for SPIFF config v2.7.4 & v3. work.
Thanks.

**Comment by EgHubs** [comment]
> Note: these three functions were removed from the ESP board library 3.0.0, make sure to use an older version, until this library is not updated.
> 
> <img alt="Screenshot 2021-06-22 at 14 01 19" width="912" src="https://user-images.githubusercontent.com/15650896/122921118-6afaa900-d362-11eb-8abb-8a0b9bdbf22c.png">

And why did they remove this feature in v3

**Comment by solariz** [comment]
Experienced the same. We are now on 3.1.2 and the Method is not working anymore.
Also jumping back with my code to 2.7.4 isnt easy throwing all kind of other dependency errors.

Going to search another way to go without BearSSL
